production:
  server: "https://analitics-private-pub.herokuapp.com/faye"

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension.

  secret_token: <%= ENV["SECRET_TOKEN_APP"] %>

  signature_expiration: 3600 # one day
